#!/bin/bash
read -p "Project? (operations, boost, yobi): " project
read -p "Task type? (fix, feat): " taskType
read -p "Message: " message
read -p "JIRA ticket: " jiraTicket

pr="[$project] [$taskType] $message"


content="JIRA ticket: \
- $jiraTicket"


hub pull-request --push --draft --message "$pr"
