#!/bin/bash

color_normal="\x1B[0m"
color_red="\x1B[31m"
color_green="\x1B[32m"
color_yellow="\x1B[33m"
color_blue="\x1B[34m"
color_magenta="\x1B[35m"
color_cyan="\x1B[36m"
color_white="\x1B[37m"

echo_color() {
  message=$1
  color=${2:-$color_normal}
  printf "$color$message $color_normal\n"
}

command -v dialog >/dev/null 2>&1 || { echo >&2 "Please install DIALOG: brew install dialog"; exit 0; }
command -v hub >/dev/null 2>&1 || { echo >&2 "Please install HUB: brew install hub"; exit 0; }

if [[ -z $(git status -s) ]]
then
  echo "Tree is clean"
else
  echo_color "\nTree is dirty, please commit changes before running! \r\n" $color_red
  exit
fi

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4

PROJECTTYPES=(
    1 "Operations"
    2 "Boost"
    3 "YOBI Design System"
)

REVIEWERSLIST=(
    1 "Gilles" off # ghaiat
    2 "Edd" off # Edd-Strickland
    3 "Tom" off # tkiddleYoobic
    4 "Miguel" off # miguelyoobic95
    5 "Raph" off # raphrak
    6 "Ondrej" off # omachala-yoobic
    7 "Wei" off # weiz18
    8 "Damien" off # darondel-yoobic
    9 "Ben A." off # benAkehurst
    10 "Ben M." off # BenMorganYobbic
    11 "Ugo" off # ubalensi-yoobic
    12 "Cam" off # crheaumet
    13 "Emilie" off # emilieYoobic
    14 "Jacob" off # Jbernardyoobic
    15 "Gabriel" off # gabides
)

PROJECTTYPE=$(dialog --clear \
            --no-cancel \
            --title " YOOBIC PULL REQUEST " \
            --menu "Choose project:" \
            $HEIGHT $WIDTH $CHOICE_HEIGHT \
            "${PROJECTTYPES[@]}" \
            2>&1 >/dev/tty)
clear

TITLE=""

case $PROJECTTYPE in
        1)
            TITLE+="Boost - "
            ;;
        2)
            TITLE+="Operations - "
            ;;
        3)
            TITLE+="YOBI - "
            ;;
esac


MESSAGE=$(dialog --title " Message " \
            --no-cancel \
            --inputbox "Describe your changes " 8 60 \
            2>&1 >/dev/tty)
clear

TITLE+=$MESSAGE

JIRA=$(dialog --title " JIRA " \
            --no-cancel \
            --inputbox "JIRA ticket URL " 8 60 \
            2>&1 >/dev/tty)
clear

REVIEWERS=$(dialog --title " Reviewers " \
            --separate-output \
            --checklist "Choose at least one reviewer" \
            22 76 16 \
            "${REVIEWERSLIST[@]}" \
            2>&1 >/dev/tty)
clear

# cmd=(dialog --separate-output --checklist "Choose at least one reviewer " 22 76 16)
# choices=$("${cmd[@]}" "${REVIEWERSLIST[@]}" 2>&1 >/dev/tty)
# clear

rews=()

for i in "${REVIEWERS[@]}"
do
   :
   case $PROJECTTYPE in
        1) rews=( "${rews[@]}" "ghaiat" ) ;;
        2) rews=( "${rews[@]}" "Edd-Strickland" ) ;;
        3) rews=( "${rews[@]}" "tkiddleYoobic" ) ;;
   esac                                                                                                   
done

bar=$(printf ",%s" "${rews[@]}")
echo $bar

# echo $REVIEWERS
# echo $TITLE
# echo $JIRA


# BODY="$TITLE \n\n
# ## PR Summary:\n\n
# ### Associated ticket:\n\n
# - $JIRA"

# hub pull-request --push --draft --message "$(printf "$BODY")"

